security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: plaintext  # ⚠️ Only use this in dev, no hashing

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # No custom_authenticators here
            stateless: false
            logout:
                path: app_logout

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: plaintext
